apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8s-ci-cd
spec:
    selector:
        matchLabels:
            app: k8s-ci-cd
    template:
        metadata:
            labels:
                app: k8s-ci-cd
        spec:
            containers:
                - name: k8s-ci-cd
                  image: erickhenrique/k8s-ci-cd:latest
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: k8s-ci-cd-service
spec:
    type: NodePort
    selector:
        app: k8s-ci-cd
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30007
